[workspace]
members = [
  "programs/dex-ai"
]

[programs.localnet]
dex_ai = "Dex111111111111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "anchor test"


